### ISSUE TITLE
Creating unique IDs in a reducer is an anti-pattern

### ISSUE THREAD

**Issue by markerikson** [Bertrand31/Monitaure#1]
Reducers are supposed to be pure functions - state+action in, new state out.  That also means that the reducer _should_ produce the exact same results for the same inputs.

The Popin reducer is generating a unique ID based on timestamps and random numbers.  This means it is _not_ going to be a pure predictable function.

The code obviously "works", but it's definitely not how Redux code is intended to be written.  I'd encourage you to move the ID generation to the Popin actions creator file instead.

See http://redux.js.org/docs/basics/Reducers.html#handling-actions , http://redux.js.org/docs/faq/Actions.html#actions-string-constants, and http://redux.js.org/docs/recipes/reducers/PrerequisiteConcepts.html for more information.

**Comment by Bertrand31** [comment]
I did know about the necessary "purity" of the reducers, just obviously didn't think about it very hard while wirting this one.
This is fixed in 20dd6eb22643f4770490ff0aeb0b5e60916ffc28.
Thank you!
