### ISSUE TITLE
UI Bug

### ISSUE THREAD

**Issue by davidbonachera** [Bertrand31/Monitaure#2]
On submit with a bad domain name. (E.g. http://www...). 
Nothing is displayed in the toast notification (top right corner). There is an empty error box.

**Comment by Bertrand31** [comment]
This is kind of a known bug, I currently can't get any error message from Sails' 500's.
I'll look into it.

**Comment by davidbonachera** [comment]
Why running sails and not a UNIX command ?

**Comment by Bertrand31** [comment]
Euh, quoi ?

**Comment by davidbonachera** [comment]
Pourquoi tu utilises sails pour ping et une commande unix ? Moyen de récuperer la réponse.

**Comment by Bertrand31** [comment]
Ah non mais je te parlais de l'erreur 500 de quand on essaye de créer un check.
Cette erreur 500 c'est Sails qui la renvoie, parce que les données entrées ne satisfont pas à certaines règles (ex: https://github.com/Bertrand31/Monitaure/blob/master/api/services/CheckManagement.js#L83).
C'est donc volontaire.

Les 'ping' sont quant à eux effectivement gérés par NodeJS, parce que ça me semble bien plus propre d'utiliser le `net.connect()` inclus de base dans NodeJS plutot que de "spawner" une commande dans un shell et d'en décortiquer péniblement le résultat.
