### ISSUE TITLE
Latency distance

### ISSUE THREAD

**Issue by davidbonachera** [Bertrand31/Monitaure#4]
I'm using a server for static file storage in Asia Pacific. My latency is around 706ms, but i guess you're only calculating this based on an european server.

Maybe you could specify a location for the ping to be executed.

Maybe i can help and deploy a server for Asia if you're interested.

**Comment by Bertrand31** [comment]
Indeed, the server is based in Roubaix (OVH FTW), hence the latency for asian servers.
That is a very good idea and a generous offer, we'll look into that once the final version is released.

**Comment by davidbonachera** [comment]
At the begin, just adding the location of the ping is enough. But in the new version, try to think about a server socket message to have a multi server location based app.
