### ISSUE TITLE
New User, Hard Coded Data

### ISSUE THREAD

**Issue by Necmttn** [Bertrand31/Monitaure#7]
![image](https://cloud.githubusercontent.com/assets/5212808/19380207/bf0b0182-9228-11e6-92d8-311b9e6ba0ff.png)
When new user login. 
sidebar has a lot of messages and reports. i think they are hardcoded. or buggy

i haven't checked source code but just i just walk trough UX.

**Comment by Bertrand31** [comment]
They are hardcoded. They will go away on the next release 😃
