### ISSUE TITLE
Monitor a specific url?

### ISSUE THREAD

**Issue by magnusottosson** [Bertrand31/Monitaure#9]
Hi,

Awesome service but is there a way to monitor a specific url? It seems like I can just input a hostname...

**Comment by Bertrand31** [comment]
Right now, the goal of Monitaure is to monitor servers on specific ports, meaning that when you enter a domain name, it is only used the get the IP address of the server you want to monitor. Therefore it doesn't make much sense to allow URLs.
That being said, webpage monitoring, with response codes and load times oversight is a functionnality that I'd very much like to add in future versions of Monitaure.
